### ISSUE TITLE
[SUGGESTION] Compat with Backported Wolves

### ISSUE THREAD

**Issue by Sunconure11** [mineblock11/WolvesOfOtherFurs#24]
https://github.com/EmilsGithub/Backported-Wolves/issues/2

https://modrinth.com/mod/backported-wolves

According to the dev, it would require more effort from both your end and his.

**Comment by IMB11** [comment]
Wont happen sorry, W.O.O.F is pretty much dead now unfortunately. I may make a spin off mod that just adds the dog bowls and beds.
